#!/bin/bash
set -e
pushd "vendor"
pushd "nginx-1.4.7"
[ -z $CONFIGURE ] || CFLAGS="-g -O0" ./configure           \
    --with-debug                      \
    --prefix=$(pwd)/../../build/nginx \
    --conf-path=conf/nginx.conf       \
    --error-log-path=logs/error.log   \
    --http-log-path=logs/access.log   \
    --add-module=../../
make
make install
popd
popd

echo SUCCESS
